project:
  type: website
  render:
    - "*.qmd"
    - "!styles/"

website:
  title: "SCVCS Research Initiative"
  # site-url: "https://oxfordroadmap.github.io/prj_SCVCS/"
  site-url: "https://scvcs.footprints.cv/"
  repo-url: "https://github.com/oxfordroadmap/prj_SCVCS"
  favicon: images/favicon.png
  # google-analytics: "UA-177339812-1"
  page-navigation: true
  search: true
  
  page-footer:
    background: "#F6F5F3"
    center: "© 2026 Liao, Han-Teng (Footprints.CV) · Proposals for EU-ASEAN Semiconductor Research Initiative · Made with {{< fa brands r-project >}} and {{< fa brands quarto >}}"
    right:
      - icon: github
        href: https://github.com/oxfordroadmap/prj_SCVCS
      - icon: envelope
        href: mailto:contact@footprints.cv

  navbar:
    search: true
    title: false
    logo: images/logo.png
    background: "#F6F5F3"
    logo-alt: "SCVCS Initiative By Footprints.CV"
    left:
      - href: index.qmd
        text: Home
      - text: "publications"
        menu:
          - text: "Working Papers"
            href: publications/working-papers.qmd # <--- And link to your new file
          # Add other publication types if they exist, like "Conference Papers" if you create a dedicated page for them later
      - href: project.qmd
        text: Project
      - href: team.qmd
        text: Team & Skills
      - href: contact.qmd
        text: Contact

  sidebar:
    - id: empty-to-suppress-sidebars-on-other-pages

format:
  html:
    theme:
      - styles/custom.scss
      - yeti
    mainfont: "Nunito Sans"
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - images
