on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write # <--- CRITICAL: Permission to verify the runner
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site  # This is where Quarto puts the HTML

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4     

